### ISSUE TITLE
brew upgrade microsoft/mssql-release/msodbcsql

### ISSUE THREAD

**Issue by minoseah629** [Microsoft/homebrew-mssql-release#9]
macOS 10.13.3 Beta (17D25b)

```
brew upgrade microsoft/mssql-release/msodbcsql
==> Upgrading 1 outdated package, with result:
microsoft/mssql-release/msodbcsql 13.1.9.0
==> Upgrading microsoft/mssql-release/msodbcsql 
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-
Already downloaded: /Users/minoseah629/Library/Caches/Homebrew/msodbcsql-13.1.9.0.tar.gz
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
Last 15 lines from /Users/xxxx/Library/Logs/Homebrew/msodbcsql/01.odbcinst:
2017-12-26 19:21:13 -0800

odbcinst -u -d -n "ODBC Driver 13 for SQL Server"

odbcinst: SQLRemoveDriver failed with General installer error.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/microsoft/homebrew-mssql-release/issues
```

**Comment by stso12** [comment]
When brew tried to do an upgrade, it uninstalled the previous version first before it installed the newer version. The problem was that it failed to uninstall the previous version. It was most probably caused by an application using the driver when brew was doing the upgrade. 
Please close all the applications that are using the ODBC driver before doing the upgrade.

**Comment by stso12** [comment]
It looked like brew didn't have access to the odbcinst.ini file when it tried to remove the section on the ODBC Driver 13 for SQL Server.

Do you install the Driver Manager 'unixODBC' manually?

**Comment by minoseah629** [comment]
brew upgrade microsoft/mssql-release/msodbcsql

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, caskroom/cask).
==> New Formulae
auditbeat       bwa             kallisto        libtomcrypt     orocos-kdl
bedops          elektra         kumo            monero          visp
blast           field3d         librealsense@1  opencascade
==> Updated Formulae
freetds ✔                                libtorrent-rasterbar
gdbm ✔                                   libu2f-server
python ✔                                 libzdb
abcmidi                                  link-grammar
ansible                                  liquigraph
ansible-lint                             lynis
antigen                                  macosvpn
apache-arrow                             macvim
arangodb                                 magic-wormhole
armadillo                                mariadb
armor                                    mikutter
artifactory                              molecule
aws-sdk-cpp                              moreutils
bash-snippets                            mpd
bear                                     mpv
bettercap                                mr
blackbox                                 mysql
blastem                                  mysql++
bowtie2                                  mysql-connector-c++
braid                                    mytop
cake                                     nano
cargo-completion                         ngrep
cgrep                                    nikto
chamber                                  node-build
check_postgres                           node@6
checkstyle                               node@8
cimg                                     nrpe
citus                                    nvc
clipper                                  onioncat
clojure                                  osm2pgrouting
closure-compiler                         osm2pgsql
coffeescript                             osquery
conjure-up                               packmol
crosstool-ng                             paket
crystal-icr                              pandoc
czmq                                     pandoc-citeproc
datomic                                  pass
davmail                                  passpie
dcm2niix                                 pdf2htmlex
debianutils                              pegtl
dependency-check                         percona-server
django-completion                        percona-toolkit
dmd                                      pex
dub                                      pg_top
duplicity                                pgpool-ii
e2fsprogs                                pianod
ejabberd                                 picard-tools
enchant                                  pick
ephemeralpg                              pigz
etcd                                     pipenv
etsh                                     pius
exim                                     plantuml
exomizer                                 platformio
exploitdb                                pod2man
fabio                                    povray
fd                                       pre-commit
fdroidserver                             pspg
feh                                      psqlodbc
fibjs                                    pwntools
flatcc                                   pypy
flow                                     python3
fluid-synth                              qt
fn                                       rancher-cli
fonttools                                rbenv-aliases
gammu                                    rbenv-binstubs
geeqie                                   rbenv-bundle-exec
get_iplayer                              rbenv-bundler
ghi                                      rbenv-bundler-ruby-version
gifsicle                                 rbenv-chefdk
gifski                                   rbenv-communal-gems
git-secret                               rbenv-ctags
gmt                                      rbenv-default-gems
gmt@4                                    rbenv-gemset
gnu-smalltalk                            rbenv-use
gnumeric                                 rbenv-vars
gnupg@2.0                                rbenv-whatis
goffice                                  re2
gopass                                   recutils
gpg-agent                                rocksdb
grib-api                                 rtv
gron                                     ruby
groonga                                  ruby@1.9
grpc                                     ruby@2.0
gsoap                                    ruby@2.1
gst-plugins-bad                          ruby@2.2
hadolint                                 ruby@2.3
haproxy                                  rust
haste-client                             s6
heroku                                   sagittarius-scheme
hg-flow                                  sbcl
hh                                       sbt
hledger                                  sccache
htop                                     shadowsocks-libev
hugo                                     shmcat
hydra                                    simgrid
ibex                                     sip
igv                                      snort
imagemagick                              sqlmap
imagemagick@6                            sslscan
innotop                                  stress-ng
irssi                                    swagger-codegen
jenkins                                  sysbench
jfrog-cli-go                             tcl-tk
jhipster                                 tclap
joplin                                   terraform_landscape
jsvc                                     tintin
just                                     tnef
karn                                     traefik
kedge                                    travis
kitchen-sync                             ttfautohint
knot                                     vim
kobalt                                   vim@7.4
kompose                                  vips
kontena                                  vultr
kpcli                                    watson
kubeless                                 weboob
kubernetes-cli                           wine
languagetool                             wpscan
ldc                                      writerperfect
libcddb                                  wtf
libcdio                                  x3270
libcds                                   xcenv
libconfig                                xxhash
libgig                                   yaf
libjson-rpc-cpp                          youtube-dl
libmspub                                 zabbix
libpqxx                                  zero-install
libpqxx@3                                zimg
librealsense                             zplug
libstfl                                  zsh

==> Upgrading 1 outdated package, with result:
microsoft/mssql-release/msodbcsql 13.1.9.0
==> Upgrading microsoft/mssql-release/msodbcsql 
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-
Already downloaded: /Users/minoseah629/Library/Caches/Homebrew/msodbcsql-13.1.9.0.tar.gz
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
Please enter YES or NO
Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
Last 15 lines from /Users/minoseah629/Library/Logs/Homebrew/msodbcsql/01.odbcinst:
2018-01-06 19:21:26 -0500

odbcinst -u -d -n "ODBC Driver 13 for SQL Server"

odbcinst: SQLRemoveDriver failed with General installer error.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/microsoft/homebrew-mssql-release/issues

These open issues may also help:
brew upgrade microsoft/mssql-release/msodbcsql https://github.com/Microsoft/homebrew-mssql-release/issues/9

xxxx:~ xxx$ brew uninstall msodbcsql
Error: Refusing to uninstall /usr/local/Cellar/msodbcsql/13.1.5.0
because it is required by mssql-tools 14.0.5.0, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies msodbcsql
xxx:~ xxx$ brew uninstall --ignore-dependencies msodbcsql
Uninstalling /usr/local/Cellar/msodbcsql/13.1.5.0... (8 files, 2.5MB)

xxx:~ xxx$ brew install microsoft/mssql-release/msodbcsql
==> Installing msodbcsql from microsoft/mssql-release
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-
Already downloaded: /Users/minoseah629/Library/Caches/Homebrew/msodbcsql-13.1.9.0.tar.gz
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
Last 15 lines from /Users/minoseah629/Library/Logs/Homebrew/msodbcsql/01.odbcinst:
2018-01-06 19:24:27 -0500

odbcinst -u -d -n "ODBC Driver 13 for SQL Server"

odbcinst: SQLRemoveDriver failed with General installer error.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/microsoft/homebrew-mssql-release/issues

These open issues may also help:
brew upgrade microsoft/mssql-release/msodbcsql https://github.com/Microsoft/homebrew-mssql-release/issues/9

**Comment by stso12** [comment]
It looks like brew has no write permission to the file odbcinst.ini file. 
Do you install driver manager manually?

Can you open a terminal and run 'odbcinst -j'?
The folder for DRIVERS should be /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini.
odbcinst -j

The output should be :
unixODBC 2. 3. 4
DRIVERS ...............................: /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/Cellar/unixodbc/2.3.4/etc/odbc.ini
.....
.....
.....

**Comment by minoseah629** [comment]
unixODBC 2.3.4
DRIVERS............: /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/Cellar/unixodbc/2.3.4/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/Cellar/unixodbc/2.3.4/etc/ODBCDataSources
USER DATA SOURCES..: /Users/xxx/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

**Comment by stso12** [comment]
Please check the followings:
1.) whether the file odbcinst.ini is existed under the folder /usr/local/Cellar/unixodbc/2.3.4/etc/
2.) if it exists, list out the contents of this file: cat /usr/local/Cellar/unixodbc/2.3.4/etc/odbcinst.ini
3.) list out the permission of the file: ls -l /usr/local/Cellar/unixodbc/2.3.4/etc
4.) check if you can see the error 'odbcinst: SQLRemoveDriver failed with General installer error' by running the command in a terminal window: odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
5.) see if you can run the command successfully if you prefix the command with sudo in the terminal window: sudo odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
6.) if it runs without the error, brew doesn't have write permission for the file odbcinst.ini. It shouldn't need sudo to modify the file.

**Comment by stso12** [comment]
The error doesn't appear. It looks like the section [ODBC Driver 13 for SQL Server] has been removed. Could you list the contents of odbcinst.ini file again? If you do the upgrade now, do you see the error 'odbcinst: SQLRemoveDriver failed with General installer error' ?

**Comment by minoseah629** [comment]
brew install microsoft/mssql-release/msodbcsql
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
==> odbcinst -i -d -f ./odbcinst.ini
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/msodbcsql/02.odbcinst.ini:
2018-01-08 20:33:13 -0500

odbcinst -i -d -f ./odbcinst.ini

odbcinst: SQLInstallDriverEx failed with Invalid install path.

**Comment by stso12** [comment]
It's a different error. I'll reply to you tomorrow.

**Comment by stso12** [comment]
It is the same problem. brew has no write permission to the odbcinst.ini file.

**Comment by minoseah629** [comment]
i got the same exact error even after uninstalling homebrew and tried again: 

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Warning: This script will remove:
/Users/xxx/Library/Caches/Homebrew/
/Users/xxx/Library/Logs/Homebrew/
/usr/local/Caskroom/
/usr/local/Cellar/
/usr/local/Homebrew/
/usr/local/Homebrew/.github/
/usr/local/Homebrew/.gitignore
/usr/local/Homebrew/.travis.yml
/usr/local/Homebrew/.yardopts
/usr/local/Homebrew/CONTRIBUTING.md
/usr/local/Homebrew/LICENSE.txt
/usr/local/Homebrew/Library/
/usr/local/Homebrew/Library/Homebrew/test/.bundle/
/usr/local/Homebrew/README.md
/usr/local/Homebrew/bin/brew
/usr/local/Homebrew/completions/
/usr/local/Homebrew/docs/
/usr/local/Homebrew/manpages/
/usr/local/bin/brew -> /usr/local/Homebrew/bin/brew
/usr/local/etc/bash_completion.d/brew -> /usr/local/Homebrew/completions/bash/brew
/usr/local/share/doc/homebrew -> /usr/local/Homebrew/docs
/usr/local/share/man/man1/brew-cask.1 -> /usr/local/Homebrew/manpages/brew-cask.1
/usr/local/share/man/man1/brew.1 -> /usr/local/Homebrew/manpages/brew.1
/usr/local/share/zsh/site-functions/_brew -> /usr/local/Homebrew/completions/zsh/_brew
/usr/local/share/zsh/site-functions/_brew_cask -> /usr/local/Homebrew/completions/zsh/_brew_cask
/usr/local/var/homebrew/locks/update
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N] y
==> Removing Homebrew installation...
==> Removing empty directories...
==> /usr/bin/sudo /usr/bin/find /usr/local/Cellar /usr/local/Homebrew /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var -name .DS_Store -delete
Password:
==> /usr/bin/sudo /usr/bin/find /usr/local/Cellar /usr/local/Homebrew /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var -depth -type d -empty -exec rmdir {} ;
==> Homebrew uninstalled!
The following possible Homebrew files were not deleted:
/usr/local/bin/
/usr/local/MacGPG2/
/usr/local/azure/
/usr/local/.com.apple.installer.keep
/usr/local/cuda/
/usr/local/microsoft/
/usr/local/include/
/usr/local/sbin/
/usr/local/remotedesktop/
/usr/local/etc/
/usr/local/var/
/usr/local/Caskroom/
/usr/local/lib/
/usr/local/lmm/
/usr/local/dualcontrol/
/usr/local/git/
/usr/local/share/
You may wish to remove them yourself.
xxx:~ xxx$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/share/man/man3
/usr/local/share/man/man8
==> The following existing directories will have their owner set to xxx:
/usr/local/share/man/man3
/usr/local/share/man/man8
==> The following existing directories will have their group set to admin:
/usr/local/share/man/man3
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Homebrew
/usr/local/Frameworks
/usr/local/opt
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
==> The Xcode Command Line Tools will be installed.

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/share/man/man3 /usr/local/share/man/man8
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/share/man/man3 /usr/local/share/man/man8
==> /usr/bin/sudo /usr/sbin/chown xxx /usr/local/share/man/man3 /usr/local/share/man/man8
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/share/man/man3
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown xxx /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /bin/mkdir -p /Users/xxx/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/xxx/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown xxx /Users/xxx/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/mkdir -p /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown xxx /Library/Caches/Homebrew
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> Installing Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.2
==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ (macOS\ High\ Sierra\ version\ 10.13)\ for\ Xcode-9.2
Software Update Tool


Downloading Command Line Tools (macOS High Sierra version 10.13) for Xcode
Downloaded Command Line Tools (macOS High Sierra version 10.13) for Xcode
Installing Command Line Tools (macOS High Sierra version 10.13) for Xcode
Done with Command Line Tools (macOS High Sierra version 10.13) for Xcode
Done.
==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
==> Downloading and installing Homebrew...
remote: Counting objects: 96100, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 96100 (delta 24), reused 28 (delta 12), pack-reused 96042
Receiving objects: 100% (96100/96100), 21.90 MiB | 16.83 MiB/s, done.
Resolving deltas: 100% (69746/69746), done.
From https://github.com/Homebrew/brew
 * [new branch]          master     -> origin/master
 * [new tag]             0.1        -> 0.1
 * [new tag]             0.2        -> 0.2
 * [new tag]             0.3        -> 0.3
 * [new tag]             0.4        -> 0.4
 * [new tag]             0.5        -> 0.5
 * [new tag]             0.6        -> 0.6
 * [new tag]             0.7        -> 0.7
 * [new tag]             0.7.1      -> 0.7.1
 * [new tag]             0.8        -> 0.8
 * [new tag]             0.8.1      -> 0.8.1
 * [new tag]             0.9        -> 0.9
 * [new tag]             0.9.1      -> 0.9.1
 * [new tag]             0.9.2      -> 0.9.2
 * [new tag]             0.9.3      -> 0.9.3
 * [new tag]             0.9.4      -> 0.9.4
 * [new tag]             0.9.5      -> 0.9.5
 * [new tag]             0.9.8      -> 0.9.8
 * [new tag]             0.9.9      -> 0.9.9
 * [new tag]             1.0.0      -> 1.0.0
 * [new tag]             1.0.1      -> 1.0.1
 * [new tag]             1.0.2      -> 1.0.2
 * [new tag]             1.0.3      -> 1.0.3
 * [new tag]             1.0.4      -> 1.0.4
 * [new tag]             1.0.5      -> 1.0.5
 * [new tag]             1.0.6      -> 1.0.6
 * [new tag]             1.0.7      -> 1.0.7
 * [new tag]             1.0.8      -> 1.0.8
 * [new tag]             1.0.9      -> 1.0.9
 * [new tag]             1.1.0      -> 1.1.0
 * [new tag]             1.1.1      -> 1.1.1
 * [new tag]             1.1.10     -> 1.1.10
 * [new tag]             1.1.11     -> 1.1.11
 * [new tag]             1.1.12     -> 1.1.12
 * [new tag]             1.1.13     -> 1.1.13
 * [new tag]             1.1.2      -> 1.1.2
 * [new tag]             1.1.3      -> 1.1.3
 * [new tag]             1.1.4      -> 1.1.4
 * [new tag]             1.1.5      -> 1.1.5
 * [new tag]             1.1.6      -> 1.1.6
 * [new tag]             1.1.7      -> 1.1.7
 * [new tag]             1.1.8      -> 1.1.8
 * [new tag]             1.1.9      -> 1.1.9
 * [new tag]             1.2.0      -> 1.2.0
 * [new tag]             1.2.1      -> 1.2.1
 * [new tag]             1.2.2      -> 1.2.2
 * [new tag]             1.2.3      -> 1.2.3
 * [new tag]             1.2.4      -> 1.2.4
 * [new tag]             1.2.5      -> 1.2.5
 * [new tag]             1.2.6      -> 1.2.6
 * [new tag]             1.3.0      -> 1.3.0
 * [new tag]             1.3.1      -> 1.3.1
 * [new tag]             1.3.2      -> 1.3.2
 * [new tag]             1.3.3      -> 1.3.3
 * [new tag]             1.3.4      -> 1.3.4
 * [new tag]             1.3.5      -> 1.3.5
 * [new tag]             1.3.6      -> 1.3.6
 * [new tag]             1.3.7      -> 1.3.7
 * [new tag]             1.3.8      -> 1.3.8
 * [new tag]             1.3.9      -> 1.3.9
 * [new tag]             1.4.0      -> 1.4.0
 * [new tag]             1.4.1      -> 1.4.1
 * [new tag]             1.4.2      -> 1.4.2
 * [new tag]             1.4.3      -> 1.4.3
HEAD is now at 987805d3d Merge pull request #3644 from MikeMcQuaid/upgrade-skip-failed-reqs
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4711, done.
remote: Compressing objects: 100% (4459/4459), done.
remote: Total 4711 (delta 54), reused 975 (delta 35), pack-reused 0
Receiving objects: 100% (4711/4711), 3.84 MiB | 11.52 MiB/s, done.
Resolving deltas: 100% (54/54), done.
Tapped 4477 formulae (4,758 files, 12MB)
==> Cleaning up /Library/Caches/Homebrew...
==> Migrating /Library/Caches/Homebrew to /Users/xxx/Library/Caches/Home
==> Deleting /Library/Caches/Homebrew...
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics.html

==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh
xxx:~ xxx$ brew install microsoft/mssql-release/msodbcsql
==> Tapping microsoft/mssql-release
Cloning into '/usr/local/Homebrew/Library/Taps/microsoft/homebrew-mssql-release'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 3), reused 5 (delta 1), pack-reused 0
Unpacking objects: 100% (8/8), done.
Tapped 4 formulae (35 files, 34.0KB)
==> Installing msodbcsql from microsoft/mssql-release
==> Installing dependencies for microsoft/mssql-release/msodbcsql: libtool, unixodbc, openssl
==> Installing microsoft/mssql-release/msodbcsql dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6_1.high_sierra
######################################################################## 100.0%
==> Pouring libtool-2.4.6_1.high_sierra.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6_1: 71 files, 3.7MB
==> Installing microsoft/mssql-release/msodbcsql dependency: unixodbc
==> Downloading https://homebrew.bintray.com/bottles/unixodbc-2.3.4.high_sierra.
######################################################################## 100.0%
==> Pouring unixodbc-2.3.4.high_sierra.bottle.2.tar.gz
🍺  /usr/local/Cellar/unixodbc/2.3.4: 43 files, 1.8MB
==> Installing microsoft/mssql-release/msodbcsql dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2n.high_sierra.
######################################################################## 100.0%
==> Pouring openssl-1.0.2n.high_sierra.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2n: 1,792 files, 12.3MB
==> Installing microsoft/mssql-release/msodbcsql
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-
######################################################################## 100.0%
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
==> odbcinst -i -d -f ./odbcinst.ini
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/msodbcsql/02.odbcinst.ini:
2018-01-08 21:53:15 -0500

odbcinst -i -d -f ./odbcinst.ini

odbcinst: SQLInstallDriverEx failed with Invalid install path.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/microsoft/homebrew-mssql-release/issues

These open issues may also help:
brew upgrade microsoft/mssql-release/msodbcsql https://github.com/Microsoft/homebrew-mssql-release/issues/9

**Comment by stso12** [comment]
Please try the followings to see if it works:
brew upgrade --no-sandbox microsoft/mssql-release/msodbcsql

**Comment by minoseah629** [comment]
brew install --no-sandbox microsoft/mssql-release/msodbcsql
==> Installing msodbcsql from microsoft/mssql-release
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-
Already downloaded: /Users/xxx/Library/Caches/Homebrew/msodbcsql-13.1.9.0.tar.gz
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
==> odbcinst -i -d -f ./odbcinst.ini
==> Caveats
If you installed this formula with the registration option (default), you'll
need to manually remove [ODBC Driver 13 for SQL Server] section from
odbcinst.ini after the formula is uninstalled. This can be done by executing
the following command:
    odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
==> Summary
🍺  /usr/local/Cellar/msodbcsql/13.1.9.0: 9 files, 2.6MB, built in 4 seconds

**Comment by Mathieuduverney** [comment]
Hello, I have the same issue but there's no odbcinst.ini (in fact I don't have /etc folder) :

$ brew install microsoft/mssql-release/msodbcsql
==> Installing msodbcsql from microsoft/mssql-release
==> Downloading http://download.microsoft.com/download/4/9/5/495639C0-79E4-45A7-B65A-B264071C3D9A/msodbcsql-13.1.9.0.tar.gz
Already downloaded: /Users/mathieuduverney/Library/Caches/Homebrew/msodbcsql-13.1.9.0.tar.gz
The license terms for this product can be downloaded from
https://aka.ms/odbc131eula and found in
/usr/local/share/doc/msodbcsql/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
==> odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
Last 15 lines from /Users/mathieuduverney/Library/Logs/Homebrew/msodbcsql/01.odbcinst:
2018-01-16 17:48:52 +0800

odbcinst -u -d -n "ODBC Driver 13 for SQL Server"

odbcinst: SQLRemoveDriver failed with Unable to find component name.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/microsoft/homebrew-mssql-release/issues

These open issues may also help:
brew upgrade microsoft/mssql-release/msodbcsql https://github.com/Microsoft/homebrew-mssql-release/issues/9

**Comment by v-chojas** [comment]
@Mathieuduverney  You do not need to build unixODBC manually, just `mkdir /usr/local/Cellar/unixodbc/2.3.5/etc` will be enough since it is empty --- it is its absence which causes the error.

The Homebrew package for unixODBC 2.3.5 is missing that directory:
 https://github.com/Homebrew/homebrew-core/issues/22938

**Comment by v-chojas** [comment]
...and now it is working again since the unixODBC 2.3.5 package is fixed.

**Comment by Mathieuduverney** [comment]
@v-chojas  Thank you very much.

Now I have a new issue:

I reinstalled everything to make it run on XAMPP, so I use php from XAMPP etc.
Everything seems to be fine, but I still can't connect from my app. Credentials are good as my teammates can connect. I have sqlsrv.so & pdo_sqlsrv.so active as I can see them on php info.

However when I call my server (method to connect to the db) I have no response from him.

Do you have any idea what and where could be the problem ?

I also edited the php.ini on XAMPP etc.

I followed this tuto using XAMPP php version (7.0.26) which works (which php : /Application/XAMPP/bin) : 

https://github.com/Microsoft/msphpsql/tree/dev#install-unix

I really do not know where is the issue...

Thank you very much !

PS: I'm on Mac Sierra

**Comment by v-chojas** [comment]
@Mathieuduverney  you should ask for PHP driver support there: https://github.com/Microsoft/msphpsql/ 

Here is Homebrew ODBC Driver for SQL Server support only.

**Comment by David-Engel** [comment]
Closing this issue. Feel free to reopen if you still have Homebrew related installation issues.

**Comment by DSLituiev** [comment]
i am getting same error. 

```odbcinst -u -d -n "ODBC Driver 13 for SQL Server"
odbcinst: SQLRemoveDriver failed with General installer error.```

there is no `/usr/local/Cellar/unixodbc/2.3.4/` folder but ` /usr/local/Cellar/unixodbc/2.3.7/`. Is it a version compatibility issue? 

Shall it be installed manually, and if so, can this be added to the installation instructions / readme?

**Comment by v-makouz** [comment]
There is a caveat message, that I believe appears during installation (and/or maybe in the description):
```
    If you installed this formula with the registration option (default), you'll
    need to manually remove [ODBC Driver 17 for SQL Server] section from
    odbcinst.ini after the formula is uninstalled. This can be done by executing
    the following command:
        odbcinst -u -d -n "ODBC Driver 17 for SQL Server"
```
